sequenceDiagram
  Enduser->>+OmegaCoin: buy-omega(amount)
  OmegaCoin->>+OmegaCoin: transfer of omega coins(amount, OmegaCoin, enduser, none)
  OmegaCoin->>+OmegaCoin: transfer of STX tokens(1000*amount, enduser, OmegaCoin)