sequenceDiagram
  Enduser->>+OmegaCoin: sell-omega(amount)
  OmegaCoin->>+OmegaCoin: transfer of omega coins(amount, endUser, OmegaCoin, none)
  OmegaCoin->>+OmegaCoin: transfer of STX tokens(1000*amount, OmegaCoin, enduser)
