sequenceDiagram
  Contract-Deployer->>Omega-Contract: deposit-omega(amount)
  Omega-Contract->>+FT-omegacoins: transfer (amount, Contract-Deployer, Omega-Contract, none)
  FT-omegacoins-->>+SIP-010-Trait: implements
  User->>Omega-Contract: buy-omega(amount) [any principal]
  Omega-Contract->>FT-omegacoins: transfer (amount, Omega-Contract, User, none)
  Contract-Deployer->>Omega-Contract: change-price(newPrice)