sequenceDiagram
  participant User 
  participant Product Store 
  participant Cosmo FT
  participant Trait Contract

  Cosmo FT  -->> Trait Contract: Implements the traits defined
  
  User ->> Product Store: add-product(name, price, quantity)
  activate  Product Store
  alt is user == contract-owner
   alt is price > 0 
    alt is quantity > 0 
     Product Store -->> Product Store : add product in inventory
     Product Store ->> User: return success
    else
    Product Store ->> User: return invalid quantity error
    end
   else
   Product Store ->> User: return invalid price error
   end
  else
  Product Store ->> User: return unauthorized caller error
  end
  deactivate Product Store

  User ->> Product Store: buy-product (name (string-ascii 50))
  activate  Product Store
  Product Store ->> Product Store: decrement-quantity(product-name)
  Product Store ->> Cosmo FT: issue-token(tokens, recipient)
  activate Cosmo FT
  alt (is valid contract-caller) || (tx-sender == contract-owner)
  Cosmo FT ->> Product Store: returns the result
  else
  Cosmo FT ->> Product Store: returns the unauthorized caller error
  end
  deactivate Cosmo FT
  Product Store ->> User: returns the result obtained from Cosmo FT
  deactivate Product Store

  User ->> Product Store: transfer-reward-tokens(amount, recipient)
  activate  Product Store
  Product Store ->> Cosmo FT: transfer(amount, sender, recipient)
  activate Cosmo FT
  alt tx-sender == sender
  Cosmo FT ->> Product Store: returns the result
  else
  Cosmo FT ->> Product Store: returns the unauthorized caller error
  end
  deactivate Cosmo FT
  Product Store ->> User: returns the result obtained from Cosmo FT
  deactivate Product Store

  User ->> Product Store: redeem-reward-tokens(amount uint)
  activate  Product Store
  Product Store ->> Cosmo FT: destroy-token(amount, owner)
  activate Cosmo FT
  alt (tx-sender == owner) || (tx-sender == contract-owner)
  Cosmo FT ->> Product Store: returns the result
  else
  Cosmo FT ->> Product Store: returns the unauthorized caller error
  end
  deactivate Cosmo FT
  Product Store ->> User: returns the result obtained from Cosmo FT
  deactivate Product Store