export const tokenMeta = [
  {
    url: "https://images-platform.99static.com//2nXI6NNRcoYdPTViJNuwlxNf1bo=/1278x8:1982x712/fit-in/500x500/99designs-contests-attachments/103/103780/attachment_103780110",
  },
  {
    url: "https://www.logoarena.com/contestimages/public_new/4280/199_1395057247_1.png",
  },
  {
    url: "https://www.kindpng.com/picc/m/675-6759669_velocity-eyewear-logo-hd-png-download.png",
  },
  {
    url: "https://images-platform.99static.com//2nXI6NNRcoYdPTViJNuwlxNf1bo=/1278x8:1982x712/fit-in/500x500/99designs-contests-attachments/103/103780/attachment_103780110",
  },
  {
    url: "https://www.logoarena.com/contestimages/public_new/4280/199_1395057247_1.png",
  },
  {
    url: "https://www.kindpng.com/picc/m/675-6759669_velocity-eyewear-logo-hd-png-download.png",
  },
  {
    url: "https://images-platform.99static.com//2nXI6NNRcoYdPTViJNuwlxNf1bo=/1278x8:1982x712/fit-in/500x500/99designs-contests-attachments/103/103780/attachment_103780110",
  },
  {
    url: "https://www.logoarena.com/contestimages/public_new/4280/199_1395057247_1.png",
  },
  {
    url: "https://www.kindpng.com/picc/m/675-6759669_velocity-eyewear-logo-hd-png-download.png",
  },
  {
    url: "https://images-platform.99static.com//2nXI6NNRcoYdPTViJNuwlxNf1bo=/1278x8:1982x712/fit-in/500x500/99designs-contests-attachments/103/103780/attachment_103780110",
  },
  {
    url: "https://www.logoarena.com/contestimages/public_new/4280/199_1395057247_1.png",
  },
  {
    url: "https://www.kindpng.com/picc/m/675-6759669_velocity-eyewear-logo-hd-png-download.png",
  },
  {
    url: "https://images-platform.99static.com//2nXI6NNRcoYdPTViJNuwlxNf1bo=/1278x8:1982x712/fit-in/500x500/99designs-contests-attachments/103/103780/attachment_103780110",
  },
  {
    url: "https://www.logoarena.com/contestimages/public_new/4280/199_1395057247_1.png",
  },
  {
    url: "https://www.kindpng.com/picc/m/675-6759669_velocity-eyewear-logo-hd-png-download.png",
  },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
  { url: "https://docs.stacks.co/images/pages/nft/nft-preview.png" },
];
